fix: fix NoSuchMethodError from IntBuffer::clear
`IntBuffer::clear`'s return type changed between JDK releases, from
Buffer to IntBuffer. This causes a NoSuchMethodError on incorrect JDKs.
Casting to Buffer ensures that the return type of Buffer will always
be used, preventing the crash. See https://stackoverflow.com/a/48694075.